test:
  image: python:3.6
  script:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt
  - pip install pytz
  - pip install coverage
  - coverage run schedulerTest.py
  - coverage report -m
